# Logging configuration

[logging.flex]

level = "debug"
console = true
file = "null"

[logging.flex.logging.LogManager]

level = "info"

[logging.flex.instances.InstanceManager]

level = "info"

[logging.flex.instances.Connector]

level = "debug"

[logging.flex.profiles.ProfileManager]

level = "warn"

[logging.flex.media.repository]

level = "warn"

[logging.flex.media.repository.MediaRepositoryManager]

level = "warn"

[logging.flex.media.repository.GitRepositoryManager]

level = "warn"

[logging.flex.media.repository.FilesystemRepositoryManager]

level = "warn"

[logging.core.client.31414]

level = "debug"

[logging.core.client.31417]

level = "debug"
