# Logging configuration

[logging.flex]

level = "info"
console = true
file = "null"

[logging.flex.logging.LogManager]

level = "warn"

[logging.flex.instances.InstanceManager]

level = "info"

[logging.flex.instances.Connector]

level = "warn"

[logging.flex.profiles.ProfileManager]

level = "info"
